language: node_js

node_js:
  - "8"

sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-2"  
  app: "nodejs-travis-elastic-beanstalk"
  env: "jenga-elastic-beanstalk-dev"
  bucket_name: "jenga-elastic-beanstalk"
  on:
    branch: master
